.TH "CCalculator" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CCalculator
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CCalculator\&.h>\fP
.PP
\fBCComponent\fP를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "HRESULT \fBReady_Calculator\fP ()"
.br
.ti -1c
.RI "\fB_float\fP \fBCompute_HeightOnTerrain\fP (const \fB_vec3\fP *pPos, const \fB_vec3\fP *pTerrainVtxPos, const \fB_ulong\fP &dwCntX=\fBVTXCNTX\fP, const \fB_ulong\fP &dwCntZ=\fBVTXCNTZ\fP, const \fB_ulong\fP &dwVtxItv=\fBVTXITV\fP)"
.br
.ti -1c
.RI "\fB_vec3\fP \fBPicking_OnTerrain\fP (HWND hWnd, const \fBCTerrainTex\fP *pTerrainBufferCom, const \fBCTransform\fP *pTerrainTransformCom)"
.br
.ti -1c
.RI "virtual \fBCComponent\fP * \fBClone\fP ()"
.br
.in -1c

\fBCComponent\fP(으)로부터 상속된 Public 멤버 함수
.in +1c
.ti -1c
.RI "virtual \fB_int\fP \fBUpdate_Component\fP (const \fB_float\fP &fTimeDelta)"
.br
.ti -1c
.RI "virtual void \fBLateUpdate_Component\fP ()"
.br
.in -1c
.SS "정적 Public 멤버 함수"

.in +1c
.ti -1c
.RI "static \fBCCalculator\fP * \fBCreate\fP (LPDIRECT3DDEVICE9 pGraphicDev)"
.br
.in -1c
.SS "추가로 상속된 멤버들"


\fBCComponent\fP(으)로부터 상속된 Protected 멤버 함수
.in +1c
.ti -1c
.RI "\fBCComponent\fP ()"
.br
.ti -1c
.RI "\fBCComponent\fP (LPDIRECT3DDEVICE9 pGraphicDev)"
.br
.ti -1c
.RI "\fBCComponent\fP (const \fBCComponent\fP &rhs)"
.br
.ti -1c
.RI "virtual \fB~CComponent\fP ()"
.br
.in -1c

\fBCComponent\fP(으)로부터 상속된 Protected 속성
.in +1c
.ti -1c
.RI "LPDIRECT3DDEVICE9 \fBm_pGraphicDev\fP"
.br
.ti -1c
.RI "\fB_bool\fP \fBm_bClone\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBCCalculator\&.h\fP 파일의 \fB9\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "\fBCComponent\fP * CCalculator::Clone ()\fR [virtual]\fP"

.PP
\fBCComponent\fP(으)로부터 재구현되었습니다\&.
.PP
\fBCCalculator\&.cpp\fP 파일의 \fB179\fP 번째 라인에서 정의되었습니다\&.
.SS "\fB_float\fP CCalculator::Compute_HeightOnTerrain (const \fB_vec3\fP * pPos, const \fB_vec3\fP * pTerrainVtxPos, const \fB_ulong\fP & dwCntX = \fR\fBVTXCNTX\fP\fP, const \fB_ulong\fP & dwCntZ = \fR\fBVTXCNTZ\fP\fP, const \fB_ulong\fP & dwVtxItv = \fR\fBVTXITV\fP\fP)"

.PP
\fBCCalculator\&.cpp\fP 파일의 \fB24\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBCCalculator\fP * CCalculator::Create (LPDIRECT3DDEVICE9 pGraphicDev)\fR [static]\fP"

.PP
\fBCCalculator\&.cpp\fP 파일의 \fB165\fP 번째 라인에서 정의되었습니다\&.
.SS "\fB_vec3\fP CCalculator::Picking_OnTerrain (HWND hWnd, const \fBCTerrainTex\fP * pTerrainBufferCom, const \fBCTransform\fP * pTerrainTransformCom)"

.PP
\fBCCalculator\&.cpp\fP 파일의 \fB63\fP 번째 라인에서 정의되었습니다\&.
.SS "HRESULT CCalculator::Ready_Calculator ()"

.PP
\fBCCalculator\&.cpp\fP 파일의 \fB19\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
