.TH "CFontMgr" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFontMgr
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CFontMgr\&.h>\fP
.PP
CBase를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "HRESULT \fBReady_Font\fP (LPDIRECT3DDEVICE9 pGraphicDev, const \fB_tchar\fP *pFontTag, const \fB_tchar\fP *pFontType, const \fB_uint\fP &iWidth, const \fB_uint\fP &iHeight, const \fB_uint\fP &iWeight)"
.br
.ti -1c
.RI "void \fBRender_Font\fP (const \fB_tchar\fP *pFontTag, const \fB_tchar\fP *pString, const \fB_vec2\fP *pPos, D3DXCOLOR Color)"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBCFontMgr\&.h\fP 파일의 \fB9\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "HRESULT CFontMgr::Ready_Font (LPDIRECT3DDEVICE9 pGraphicDev, const \fB_tchar\fP * pFontTag, const \fB_tchar\fP * pFontType, const \fB_uint\fP & iWidth, const \fB_uint\fP & iHeight, const \fB_uint\fP & iWeight)"

.PP
\fBCFontMgr\&.cpp\fP 파일의 \fB14\fP 번째 라인에서 정의되었습니다\&.
.SS "void CFontMgr::Render_Font (const \fB_tchar\fP * pFontTag, const \fB_tchar\fP * pString, const \fB_vec2\fP * pPos, D3DXCOLOR Color)"

.PP
\fBCFontMgr\&.cpp\fP 파일의 \fB31\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
