.TH "CFrameMgr" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CFrameMgr
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CFrameMgr\&.h>\fP
.PP
CBase를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fB_bool\fP \fBIsPermit_Call\fP (const \fB_tchar\fP *pFrameTag, const \fB_float\fP &fTimeDelta)"
.br
.ti -1c
.RI "HRESULT \fBReady_Frame\fP (const \fB_tchar\fP *pFrameTag, const \fB_float\fP &fCallLimit)"
.br
.ti -1c
.RI "virtual void \fBFree\fP ()"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBCFrameMgr\&.h\fP 파일의 \fB8\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "void CFrameMgr::Free ()\fR [virtual]\fP"

.PP
\fBCFrameMgr\&.cpp\fP 파일의 \fB49\fP 번째 라인에서 정의되었습니다\&.
.SS "\fB_bool\fP CFrameMgr::IsPermit_Call (const \fB_tchar\fP * pFrameTag, const \fB_float\fP & fTimeDelta)"

.PP
\fBCFrameMgr\&.cpp\fP 파일의 \fB14\fP 번째 라인에서 정의되었습니다\&.
.SS "HRESULT CFrameMgr::Ready_Frame (const \fB_tchar\fP * pFrameTag, const \fB_float\fP & fCallLimit)"

.PP
\fBCFrameMgr\&.cpp\fP 파일의 \fB23\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
