.TH "C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/CInteractMgr.h" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/CInteractMgr.h \- 상호작용 오브젝트 통합 관리 싱글톤 매니저 클래스  

.SH SYNOPSIS
.br
.PP
\fR#include 'CBase\&.h'\fP
.br
\fR#include 'Engine_Define\&.h'\fP
.br
\fR#include 'CGameObject\&.h'\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBCInteractMgr\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
상호작용 오브젝트 통합 관리 싱글톤 매니저 클래스 


.PP
\fB날짜\fP
.RS 4
2025-07-02 
.RE
.PP
\fB작성자\fP
.RS 4
권예지
.RE
.PP
플레이어가 상호작용 가능한 오브젝트(CInteract 기반)를 종류별로 관리하는 싱글톤 매니저 클래스\&. 들 수 있는 오브젝트, 고정 작업대로 구분하여 리스트로 관리하며, 리스트 추가, 조회, 삭제 가능\&. 
.PP
\fBCInteractMgr\&.h\fP 파일에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
