.TH "C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/CLightMgr.h" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/CLightMgr.h
.SH SYNOPSIS
.br
.PP
\fR#include 'CBase\&.h'\fP
.br
\fR#include 'CLight\&.h'\fP
.br
\fR#include 'Engine_Define\&.h'\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBCLightMgr\fP"
.br
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
