.TH "CMapTool" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMapTool
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CMapTool\&.h>\fP
.PP
CBase를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "HRESULT \fBLoad_Json\fP ()"
.br
.ti -1c
.RI "map< string, \fBS_STAGE\fP > * \fBGet_MapInfo\fP ()"
.br
.RI "json 데이터 불러오기 "
.ti -1c
.RI "\fBS_STAGE\fP \fBGet_Data\fP (string s)"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBCMapTool\&.h\fP 파일의 \fB89\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "\fBS_STAGE\fP CMapTool::Get_Data (string s)"

.PP
\fBCMapTool\&.cpp\fP 파일의 \fB57\fP 번째 라인에서 정의되었습니다\&.
.SS "map< string, \fBS_STAGE\fP > * CMapTool::Get_MapInfo ()\fR [inline]\fP"

.PP
json 데이터 불러오기 
.PP
\fBCMapTool\&.h\fP 파일의 \fB99\fP 번째 라인에서 정의되었습니다\&.
.SS "HRESULT CMapTool::Load_Json ()"

.PP
\fBCMapTool\&.cpp\fP 파일의 \fB27\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
