.TH "C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Code/CMapTool.cpp" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Code/CMapTool.cpp
.SH SYNOPSIS
.br
.PP
\fR#include '\&.\&./Header/json\&.hpp'\fP
.br
\fR#include 'CMapTool\&.h'\fP
.br
\fR#include <fstream>\fP
.br

.SS "타입정의"

.in +1c
.ti -1c
.RI "using \fBjson\fP = nlohmann::json"
.br
.in -1c
.SS "함수"

.in +1c
.ti -1c
.RI "\fBNLOHMANN_DEFINE_TYPE_NON_INTRUSIVE\fP (\fBS_STAGE\fP, Cam, Player, Time, Recipe, GameObject, Environment)"
.br
.in -1c
.SH "타입정의 문서화"
.PP 
.SS "using \fBjson\fP = nlohmann::json"

.PP
\fBCMapTool\&.cpp\fP 파일의 \fB5\fP 번째 라인에서 정의되었습니다\&.
.SH "함수 문서화"
.PP 
.SS "NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE (\fBS_STAGE\fP , Cam , Player , Time , Recipe , GameObject , Environment )"

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
