.TH "C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/CMapTool.h" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/CMapTool.h
.SH SYNOPSIS
.br
.PP
\fR#include 'CBase\&.h'\fP
.br
\fR#include 'Engine_Define\&.h'\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "struct \fBS_BLOCK\fP"
.br
.RI "블럭 구조체 "
.ti -1c
.RI "struct \fBS_TILE\fP"
.br
.ti -1c
.RI "struct \fBS_GAMEOBJECT\fP"
.br
.ti -1c
.RI "struct \fBS_ENVIRONMENT\fP"
.br
.RI "환경 구조물 구조체 "
.ti -1c
.RI "struct \fBS_CAM\fP"
.br
.RI "카메라를 저장할 벡터 구조체 "
.ti -1c
.RI "struct \fBS_PLAYER\fP"
.br
.RI "카메라를 저장할 벡터 구조체 "
.ti -1c
.RI "struct \fBS_STAGE\fP"
.br
.RI "스테이지의 모든 정보를 가진 구조체 "
.ti -1c
.RI "class \fBCMapTool\fP"
.br
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
