.TH "C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/CObjectPoolMgr.h" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/CObjectPoolMgr.h \- 게임 오브젝트 풀을 관리하는 싱글톤 클래스  

.SH SYNOPSIS
.br
.PP
\fR#include 'Engine_Define\&.h'\fP
.br
\fR#include 'CGameObject\&.h'\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBCObjectPoolMgr\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
게임 오브젝트 풀을 관리하는 싱글톤 클래스 


.PP
\fB날짜\fP
.RS 4
2025-07-09 
.RE
.PP
\fB작성자\fP
.RS 4
권예지
.RE
.PP
이 클래스는 자주 생성 및 삭제되는 게임 오브젝트들을 미리 생성해 재사용하는 오브젝트 풀링 시스템을 관리
.IP "\(bu" 2
오브젝트 등록 및 반환
.IP "\(bu" 2
오브젝트 조회 
.PP

.PP
\fBCObjectPoolMgr\&.h\fP 파일에서 정의되었습니다\&.
.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
