.TH "CProtoMgr" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CProtoMgr
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CProtoMgr\&.h>\fP
.PP
CBase를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "HRESULT \fBReady_Prototype\fP (const \fB_tchar\fP *pComponentTag, \fBCComponent\fP *pComponent)"
.br
.ti -1c
.RI "\fBCComponent\fP * \fBClone_Prototype\fP (const \fB_tchar\fP *pComponentTag)"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBCProtoMgr\&.h\fP 파일의 \fB19\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "\fBCComponent\fP * CProtoMgr::Clone_Prototype (const \fB_tchar\fP * pComponentTag)"

.PP
\fBCProtoMgr\&.cpp\fP 파일의 \fB25\fP 번째 라인에서 정의되었습니다\&.
.SS "HRESULT CProtoMgr::Ready_Prototype (const \fB_tchar\fP * pComponentTag, \fBCComponent\fP * pComponent)"

.PP
\fBCProtoMgr\&.cpp\fP 파일의 \fB14\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
