.TH "C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/CProtoMgr.h" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/CProtoMgr.h
.SH SYNOPSIS
.br
.PP
\fR#include 'CBase\&.h'\fP
.br
\fR#include 'CComponent\&.h'\fP
.br
\fR#include 'CRcTex\&.h'\fP
.br
\fR#include 'CRcCol\&.h'\fP
.br
\fR#include 'CTriCol\&.h'\fP
.br
\fR#include 'CTerrainTex\&.h'\fP
.br
\fR#include 'CCubeTex\&.h'\fP
.br
\fR#include 'CTransform\&.h'\fP
.br
\fR#include 'CTexture\&.h'\fP
.br
\fR#include 'CCalculator\&.h'\fP
.br
\fR#include 'CFSMComponent\&.h'\fP
.br

.SS "클래스"

.in +1c
.ti -1c
.RI "class \fBCProtoMgr\fP"
.br
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
