.TH "CSprite" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSprite
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CSprite\&.h>\fP
.PP
\fBCComponent\fP를(을) 상속했습니다\&.
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "HRESULT \fBReady_Sprite\fP (const \fB_tchar\fP *pPath, \fBSPRITE_ID\fP eType, const \fB_uint\fP &iCnt, LPDIRECT3DDEVICE9 pGraphicDev)"
.br
.ti -1c
.RI "void \fBRender_Sprite\fP (D3DXVECTOR3 _m_vPos, int _Index=0, int _m_iAlpha=255)"
.br
.ti -1c
.RI "\fBCSprite\fP * \fBClone\fP () override"
.br
.in -1c

\fBCComponent\fP(으)로부터 상속된 Public 멤버 함수
.in +1c
.ti -1c
.RI "virtual \fB_int\fP \fBUpdate_Component\fP (const \fB_float\fP &fTimeDelta)"
.br
.ti -1c
.RI "virtual void \fBLateUpdate_Component\fP ()"
.br
.in -1c
.SS "정적 Public 멤버 함수"

.in +1c
.ti -1c
.RI "static \fBCSprite\fP * \fBCreate\fP (LPDIRECT3DDEVICE9 pGraphicDev, const \fB_tchar\fP *pPath, \fBSPRITE_ID\fP eType, const \fB_uint\fP &iCnt=1)"
.br
.in -1c
.SS "추가로 상속된 멤버들"


\fBCComponent\fP(으)로부터 상속된 Protected 멤버 함수
.in +1c
.ti -1c
.RI "\fBCComponent\fP ()"
.br
.ti -1c
.RI "\fBCComponent\fP (LPDIRECT3DDEVICE9 pGraphicDev)"
.br
.ti -1c
.RI "\fBCComponent\fP (const \fBCComponent\fP &rhs)"
.br
.ti -1c
.RI "virtual \fB~CComponent\fP ()"
.br
.in -1c

\fBCComponent\fP(으)로부터 상속된 Protected 속성
.in +1c
.ti -1c
.RI "LPDIRECT3DDEVICE9 \fBm_pGraphicDev\fP"
.br
.ti -1c
.RI "\fB_bool\fP \fBm_bClone\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBCSprite\&.h\fP 파일의 \fB7\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "\fBCSprite\fP * CSprite::Clone ()\fR [inline]\fP, \fR [override]\fP, \fR [virtual]\fP"

.PP
\fBCComponent\fP(으)로부터 재구현되었습니다\&.
.PP
\fBCSprite\&.h\fP 파일의 \fB26\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBCSprite\fP * CSprite::Create (LPDIRECT3DDEVICE9 pGraphicDev, const \fB_tchar\fP * pPath, \fBSPRITE_ID\fP eType, const \fB_uint\fP & iCnt = \fR1\fP)\fR [static]\fP"

.PP
\fBCSprite\&.cpp\fP 파일의 \fB67\fP 번째 라인에서 정의되었습니다\&.
.SS "HRESULT CSprite::Ready_Sprite (const \fB_tchar\fP * pPath, \fBSPRITE_ID\fP eType, const \fB_uint\fP & iCnt, LPDIRECT3DDEVICE9 pGraphicDev)"

.PP
\fBCSprite\&.cpp\fP 파일의 \fB25\fP 번째 라인에서 정의되었습니다\&.
.SS "void CSprite::Render_Sprite (D3DXVECTOR3 _m_vPos, int _Index = \fR0\fP, int _m_iAlpha = \fR255\fP)"

.PP
\fBCSprite\&.cpp\fP 파일의 \fB50\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
