.TH "detail::detector< Default, void_t< Op< Args... > >, Op, Args... >" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::detector< Default, void_t< Op< Args... > >, Op, Args... >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.SS "Public 타입"

.in +1c
.ti -1c
.RI "using \fBvalue_t\fP = std::true_type"
.br
.ti -1c
.RI "using \fBtype\fP = Op<Args\&.\&.\&.>"
.br
.in -1c
.SH "상세한 설명"
.PP 

.SS "template<class Default, template< class\&.\&.\&. > class Op, class\&.\&.\&. Args>
.br
struct detail::detector< Default, void_t< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >"
.PP
\fBjson\&.hpp\fP 파일의 \fB298\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 타입정의 문서화"
.PP 
.SS "template<class Default, template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBdetail::detector\fP< Default, \fBvoid_t\fP< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >::type = Op<Args\&.\&.\&.>"

.PP
\fBjson\&.hpp\fP 파일의 \fB301\fP 번째 라인에서 정의되었습니다\&.
.SS "template<class Default, template< class\&.\&.\&. > class Op, class\&.\&.\&. Args> using \fBdetail::detector\fP< Default, \fBvoid_t\fP< Op< Args\&.\&.\&. > >, Op, Args\&.\&.\&. >::value_t = std::true_type"

.PP
\fBjson\&.hpp\fP 파일의 \fB300\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
