.TH "detail::is_c_string< T >" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::is_c_string< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.PP
bool_constant< impl::is_c_string< T >()>를(을) 상속했습니다\&.
.SH "상세한 설명"
.PP 

.SS "template<typename T>
.br
struct detail::is_c_string< T >"
.PP
\fBjson\&.hpp\fP 파일의 \fB4337\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
