.TH "detail::is_comparable< Compare, A, B, typename >" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
detail::is_comparable< Compare, A, B, typename >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <json\&.hpp>\fP
.PP
std::false_type를(을) 상속했습니다\&.
.SH "상세한 설명"
.PP 

.SS "template<typename Compare, typename A, typename B, typename = void>
.br
struct detail::is_comparable< Compare, A, B, typename >"
.PP
\fBjson\&.hpp\fP 파일의 \fB4133\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
