.TH "Engine::CTag_Finder" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Engine::CTag_Finder
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Engine_Function\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBCTag_Finder\fP (const \fB_tchar\fP *pTag)"
.br
.ti -1c
.RI "\fB~CTag_Finder\fP (void)"
.br
.ti -1c
.RI "template<typename T> \fB_bool\fP \fBoperator()\fP (const T &pair)"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBEngine_Function\&.h\fP 파일의 \fB49\fP 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "Engine::CTag_Finder::CTag_Finder (const \fB_tchar\fP * pTag)\fR [inline]\fP, \fR [explicit]\fP"

.PP
\fBEngine_Function\&.h\fP 파일의 \fB52\fP 번째 라인에서 정의되었습니다\&.
.SS "Engine::CTag_Finder::~CTag_Finder (void )\fR [inline]\fP"

.PP
\fBEngine_Function\&.h\fP 파일의 \fB53\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "template<typename T> \fB_bool\fP Engine::CTag_Finder::operator() (const T & pair)\fR [inline]\fP"

.PP
\fBEngine_Function\&.h\fP 파일의 \fB57\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
