.TH "Engine::CDeleteObj" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Engine::CDeleteObj
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Engine_Function\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBCDeleteObj\fP (void)"
.br
.ti -1c
.RI "\fB~CDeleteObj\fP (void)"
.br
.ti -1c
.RI "template<typename T> void \fBoperator()\fP (T &pInstance)"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBEngine_Function\&.h\fP 파일의 \fB69\fP 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "Engine::CDeleteObj::CDeleteObj (void )\fR [inline]\fP, \fR [explicit]\fP"

.PP
\fBEngine_Function\&.h\fP 파일의 \fB72\fP 번째 라인에서 정의되었습니다\&.
.SS "Engine::CDeleteObj::~CDeleteObj (void )\fR [inline]\fP"

.PP
\fBEngine_Function\&.h\fP 파일의 \fB73\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "template<typename T> void Engine::CDeleteObj::operator() (T & pInstance)\fR [inline]\fP"

.PP
\fBEngine_Function\&.h\fP 파일의 \fB76\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
