.TH "Engine/Header/Engine_Enum.h" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Engine/Header/Engine_Enum.h
.SH SYNOPSIS
.br
.PP
.SS "네임스페이스"

.in +1c
.ti -1c
.RI "namespace \fBEngine\fP"
.br
.in -1c
.SS "열거형 타입"

.in +1c
.ti -1c
.RI "enum \fBEngine::WINMODE\fP { \fBEngine::MODE_FULL\fP, \fBEngine::MODE_WIN\fP }"
.br
.ti -1c
.RI "enum \fBEngine::COMPONENTID\fP { \fBEngine::ID_DYNAMIC\fP, \fBEngine::ID_STATIC\fP, \fBEngine::ID_END\fP }"
.br
.ti -1c
.RI "enum \fBEngine::INFO\fP { \fBEngine::INFO_RIGHT\fP, \fBEngine::INFO_UP\fP, \fBEngine::INFO_LOOK\fP, \fBEngine::INFO_POS\fP, \fBEngine::INFO_END\fP }"
.br
.ti -1c
.RI "enum \fBEngine::ROTATION\fP { \fBEngine::ROT_X\fP, \fBEngine::ROT_Y\fP, \fBEngine::ROT_Z\fP, \fBEngine::ROT_END\fP }"
.br
.ti -1c
.RI "enum \fBEngine::TEXTUREID\fP { \fBEngine::TEX_NORMAL\fP, \fBEngine::TEX_CUBE\fP, \fBEngine::TEX_END\fP }"
.br
.ti -1c
.RI "enum \fBEngine::RENDERID\fP { \fBEngine::RENDER_PRIORITY\fP, \fBEngine::RENDER_NONALPHA\fP, \fBEngine::RENDER_ALPHA\fP, \fBEngine::RENDER_UI\fP, \fBEngine::RENDER_END\fP }"
.br
.ti -1c
.RI "enum \fBEngine::MOUSEKEYSTATE\fP { \fBEngine::DIM_LB\fP, \fBEngine::DIM_RB\fP, \fBEngine::DIM_MB\fP, \fBEngine::DIM_END\fP }"
.br
.ti -1c
.RI "enum \fBEngine::MOUSEMOVESTATE\fP { \fBEngine::DIMS_X\fP, \fBEngine::DIMS_Y\fP, \fBEngine::DIMS_Z\fP, \fBEngine::DIMS_END\fP }"
.br
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
