.TH "C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/Engine_Typedef.h" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anjunhyeong/Documents/jusin/SR_Overcooked2/Engine/Header/Engine_Typedef.h
.SH SYNOPSIS
.br
.PP
.SS "네임스페이스"

.in +1c
.ti -1c
.RI "namespace \fBEngine\fP"
.br
.in -1c
.SS "타입정의"

.in +1c
.ti -1c
.RI "typedef bool \fBEngine::_bool\fP"
.br
.ti -1c
.RI "typedef signed char \fBEngine::_byte\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBEngine::_ubyte\fP"
.br
.ti -1c
.RI "typedef wchar_t \fBEngine::_tchar\fP"
.br
.ti -1c
.RI "typedef signed short \fBEngine::_short\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBEngine::_ushort\fP"
.br
.ti -1c
.RI "typedef signed int \fBEngine::_int\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBEngine::_uint\fP"
.br
.ti -1c
.RI "typedef signed long \fBEngine::_long\fP"
.br
.ti -1c
.RI "typedef unsigned long \fBEngine::_ulong\fP"
.br
.ti -1c
.RI "typedef float \fBEngine::_float\fP"
.br
.ti -1c
.RI "typedef double \fBEngine::_double\fP"
.br
.ti -1c
.RI "typedef D3DXVECTOR2 \fBEngine::_vec2\fP"
.br
.ti -1c
.RI "typedef D3DXVECTOR3 \fBEngine::_vec3\fP"
.br
.ti -1c
.RI "typedef D3DXVECTOR4 \fBEngine::_vec4\fP"
.br
.ti -1c
.RI "typedef D3DXMATRIX \fBEngine::_matrix\fP"
.br
.in -1c
.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
