.TH "Engine::CDeleteMap" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Engine::CDeleteMap
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <Engine_Function\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBCDeleteMap\fP (void)"
.br
.ti -1c
.RI "\fB~CDeleteMap\fP (void)"
.br
.ti -1c
.RI "template<typename T> void \fBoperator()\fP (T &Pair)"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBEngine_Function\&.h\fP 파일의 \fB88\fP 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "Engine::CDeleteMap::CDeleteMap (void )\fR [inline]\fP, \fR [explicit]\fP"

.PP
\fBEngine_Function\&.h\fP 파일의 \fB91\fP 번째 라인에서 정의되었습니다\&.
.SS "Engine::CDeleteMap::~CDeleteMap (void )\fR [inline]\fP"

.PP
\fBEngine_Function\&.h\fP 파일의 \fB92\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "template<typename T> void Engine::CDeleteMap::operator() (T & Pair)\fR [inline]\fP"

.PP
\fBEngine_Function\&.h\fP 파일의 \fB95\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
