.TH "IPhysics::PHYSICS_OPT" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPhysics::PHYSICS_OPT
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IPhysics\&.h>\fP
.SS "Public 속성"

.in +1c
.ti -1c
.RI "\fB_bool\fP \fBbApplyCollision\fP = true"
.br
.ti -1c
.RI "\fB_bool\fP \fBbApplyGravity\fP = true"
.br
.ti -1c
.RI "\fB_bool\fP \fBbApplyRolling\fP = false"
.br
.ti -1c
.RI "\fB_bool\fP \fBbApplyBouncing\fP = false"
.br
.ti -1c
.RI "\fB_bool\fP \fBbApplyKnockBack\fP = false"
.br
.ti -1c
.RI "\fB_bool\fP \fBbThrown\fP = false"
.br
.ti -1c
.RI "\fB_bool\fP \fBbFirstThrown\fP = false"
.br
.ti -1c
.RI "\fB_float\fP \fBfDeceleration\fP = 0\&.98f"
.br
.ti -1c
.RI "\fBBOUNDING_TYPE\fP \fBeBoundingType\fP = \fBBOX\fP"
.br
.ti -1c
.RI "\fBCOLLISION_OPT\fP \fBstCollisionOpt\fP = \fBAABB\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBIPhysics\&.h\fP 파일의 \fB20\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 데이터 문서화"
.PP 
.SS "\fB_bool\fP IPhysics::PHYSICS_OPT::bApplyBouncing = false"

.PP
\fBIPhysics\&.h\fP 파일의 \fB24\fP 번째 라인에서 정의되었습니다\&.
.SS "\fB_bool\fP IPhysics::PHYSICS_OPT::bApplyCollision = true"

.PP
\fBIPhysics\&.h\fP 파일의 \fB21\fP 번째 라인에서 정의되었습니다\&.
.SS "\fB_bool\fP IPhysics::PHYSICS_OPT::bApplyGravity = true"

.PP
\fBIPhysics\&.h\fP 파일의 \fB22\fP 번째 라인에서 정의되었습니다\&.
.SS "\fB_bool\fP IPhysics::PHYSICS_OPT::bApplyKnockBack = false"

.PP
\fBIPhysics\&.h\fP 파일의 \fB25\fP 번째 라인에서 정의되었습니다\&.
.SS "\fB_bool\fP IPhysics::PHYSICS_OPT::bApplyRolling = false"

.PP
\fBIPhysics\&.h\fP 파일의 \fB23\fP 번째 라인에서 정의되었습니다\&.
.SS "\fB_bool\fP IPhysics::PHYSICS_OPT::bFirstThrown = false"

.PP
\fBIPhysics\&.h\fP 파일의 \fB27\fP 번째 라인에서 정의되었습니다\&.
.SS "\fB_bool\fP IPhysics::PHYSICS_OPT::bThrown = false"

.PP
\fBIPhysics\&.h\fP 파일의 \fB26\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBBOUNDING_TYPE\fP IPhysics::PHYSICS_OPT::eBoundingType = \fBBOX\fP"

.PP
\fBIPhysics\&.h\fP 파일의 \fB29\fP 번째 라인에서 정의되었습니다\&.
.SS "\fB_float\fP IPhysics::PHYSICS_OPT::fDeceleration = 0\&.98f"

.PP
\fBIPhysics\&.h\fP 파일의 \fB28\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBCOLLISION_OPT\fP IPhysics::PHYSICS_OPT::stCollisionOpt = \fBAABB\fP"

.PP
\fBIPhysics\&.h\fP 파일의 \fB30\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
