.TH "IShadow" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IShadow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <IShadow\&.h>\fP
.SS "Public 멤버 함수"

.in +1c
.ti -1c
.RI "\fBIShadow\fP ()"
.br
.ti -1c
.RI "\fBIShadow\fP (LPDIRECT3DDEVICE9 _pGraphicDev)"
.br
.ti -1c
.RI "const LPDIRECT3DDEVICE9 \fBGet_GraphicDev\fP ()"
.br
.in -1c
.SS "Protected 속성"

.in +1c
.ti -1c
.RI "LPDIRECT3DDEVICE9 \fBm_pShadowGraphicDev\fP = nullptr"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBIShadow\&.h\fP 파일의 \fB3\fP 번째 라인에서 정의되었습니다\&.
.SH "생성자 & 소멸자 문서화"
.PP 
.SS "IShadow::IShadow ()\fR [inline]\fP"

.PP
\fBIShadow\&.h\fP 파일의 \fB5\fP 번째 라인에서 정의되었습니다\&.
.SS "IShadow::IShadow (LPDIRECT3DDEVICE9 _pGraphicDev)\fR [inline]\fP"

.PP
\fBIShadow\&.h\fP 파일의 \fB6\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 함수 문서화"
.PP 
.SS "const LPDIRECT3DDEVICE9 IShadow::Get_GraphicDev ()\fR [inline]\fP"

.PP
\fBIShadow\&.h\fP 파일의 \fB12\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 데이터 문서화"
.PP 
.SS "LPDIRECT3DDEVICE9 IShadow::m_pShadowGraphicDev = nullptr\fR [protected]\fP"

.PP
\fBIShadow\&.h\fP 파일의 \fB9\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
