.TH "S_GAMEOBJECT" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S_GAMEOBJECT
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CMapTool\&.h>\fP
.SS "Public 속성"

.in +1c
.ti -1c
.RI "std::vector< \fBS_BLOCK\fP > \fBBlock\fP"
.br
.ti -1c
.RI "std::vector< \fBS_TILE\fP > \fBTile\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
\fBCMapTool\&.h\fP 파일의 \fB41\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 데이터 문서화"
.PP 
.SS "std::vector<\fBS_BLOCK\fP> S_GAMEOBJECT::Block"

.PP
\fBCMapTool\&.h\fP 파일의 \fB42\fP 번째 라인에서 정의되었습니다\&.
.SS "std::vector<\fBS_TILE\fP> S_GAMEOBJECT::Tile"

.PP
\fBCMapTool\&.h\fP 파일의 \fB43\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
