.TH "S_STAGE" 3 "Version 1.0" "Engine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S_STAGE \- 스테이지의 모든 정보를 가진 구조체  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CMapTool\&.h>\fP
.SS "Public 속성"

.in +1c
.ti -1c
.RI "\fBS_CAM\fP \fBCam\fP"
.br
.ti -1c
.RI "\fBS_PLAYER\fP \fBPlayer\fP"
.br
.ti -1c
.RI "float \fBTime\fP"
.br
.ti -1c
.RI "std::vector< string > \fBRecipe\fP"
.br
.ti -1c
.RI "\fBS_GAMEOBJECT\fP \fBGameObject\fP"
.br
.ti -1c
.RI "std::vector< \fBS_ENVIRONMENT\fP > \fBEnvironment\fP"
.br
.in -1c
.SH "상세한 설명"
.PP 
스테이지의 모든 정보를 가진 구조체 
.PP
\fBCMapTool\&.h\fP 파일의 \fB78\fP 번째 라인에서 정의되었습니다\&.
.SH "멤버 데이터 문서화"
.PP 
.SS "\fBS_CAM\fP S_STAGE::Cam"

.PP
\fBCMapTool\&.h\fP 파일의 \fB79\fP 번째 라인에서 정의되었습니다\&.
.SS "std::vector<\fBS_ENVIRONMENT\fP> S_STAGE::Environment"

.PP
\fBCMapTool\&.h\fP 파일의 \fB84\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBS_GAMEOBJECT\fP S_STAGE::GameObject"

.PP
\fBCMapTool\&.h\fP 파일의 \fB83\fP 번째 라인에서 정의되었습니다\&.
.SS "\fBS_PLAYER\fP S_STAGE::Player"

.PP
\fBCMapTool\&.h\fP 파일의 \fB80\fP 번째 라인에서 정의되었습니다\&.
.SS "std::vector<string> S_STAGE::Recipe"

.PP
\fBCMapTool\&.h\fP 파일의 \fB82\fP 번째 라인에서 정의되었습니다\&.
.SS "float S_STAGE::Time"

.PP
\fBCMapTool\&.h\fP 파일의 \fB81\fP 번째 라인에서 정의되었습니다\&.

.SH "작성자"
.PP 
소스 코드로부터 Engine를 위해 Doxygen에 의해 자동으로 생성됨\&.
