#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	enum WINMODE { MODE_FULL, MODE_WIN };

	// Dynamic 컴포넌트 경우 매 프레임마다 갱신해야하는 컴포넌트 집단
	enum COMPONENTID { ID_DYNAMIC, ID_STATIC, ID_END };

	enum INFO { INFO_RIGHT, INFO_UP, INFO_LOOK, INFO_POS, INFO_END };
	enum ROTATION { ROT_X, ROT_Y, ROT_Z, ROT_END };

	enum TEXTUREID { TEX_NORMAL, TEX_CUBE, TEX_END };

	enum RENDERID { RENDER_PRIORITY, RENDER_NONALPHA, RENDER_ALPHA, RENDER_UI, RENDER_END };

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };
	
	
	enum BUTTON_TYPE { STORY_BUTTON, ARCADE_BUTTON, BATTLE_BUTTON, CHEF_BUTTON, STATE_BUTTON, OK_BUTTON, NO_BUTTON, END_BUTTON };
	enum GAUGE_TYPE { IMAGE_GAUGE, IMAGE2_GAUGE, LODING_GAUGE, FONT_GAUGE, END_GAUGE };
	enum OBJECT_TYPE { IMAGE_OBJECT, BOX_OBJECT, GAUGE_OBJECT, END_OBJECT };
}
#endif // Engine_Enum_h__
